# Generated by Django 5.2.8 on 2025-12-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_teachersubject_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
